name: YourCloset
options:
  bundleIdPrefix: hikaru.hara
  developmentLanguage: ja
  deploymentTarget:
    iOS: 13.0
  xcodeVersion: "12.2"
settings:
  configs:
    debug:
      CODE_SIGN_IDENTITY: iPhone Developer
      DEVELOPMENT_TEAM: R6FXVG8497
    release:
      CODE_SIGN_IDENTITY: iPhone Distribution
      DEVELOPMENT_TEAM: R6FXVG8497
targets:
  YourCloset:
    type: application
    platform: iOS
    sources:
      - YourCloset
    dependencies:
      - target: Util
      - target: UIComponent
      - target: Infra
  YourClosetTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - YourClosetTests
  YourClosetUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - YourClosetUITests
  Util:
    type: framework
    platform: iOS
    sources:
      - Util
  UIComponent:
    type: framework
    platform: iOS
    sources:
      - UIComponent
    dependencies:
      - target: Util
  Infra:
    type: framework
    platform: iOS
    sources:
      - Infra
    dependencies:
      - target: Util
