name: YourCloset
options:
  bundleIdPrefix: hikaru.hara
  developmentLanguage: ja
  deploymentTarget:
    iOS: 13.0
  xcodeVersion: "12.2"
targets:
  YourCloset:
    type: application
    platform: iOS
    sources:
      - YourCloset
    dependencies:
      - target: Util
      - target: UIComponent
  YourClosetTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - YourClosetTests
  YourClosetUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - YourClosetUITests
  Util:
    type: framework
    platform: iOS
    sources:
      - Util
  UIComponent:
    type: framework
    platform: iOS
    sources:
      - UIComponent
    dependencies:
      - target: Util
